# Hypothesis Testing

In [51]:
import pandas as pd
from scipy import stats

In [52]:
df = pd.read_csv('pizza_sales.csv')

# One Sample T-Test

# Is the average total price of all pizza sales different from $15?

In [53]:
alpha = 0.05
sample  = 15
population = df['total_price']

In [54]:
#stats.ttest_1samp(population, popmean = sample)
t_statistics,p_value = stats.ttest_1samp(population, popmean = sample)

In [55]:
import numpy as np
actual_mean = population.mean()
sd = population.std()
total_data =np.sqrt(48619)

In [56]:
#Statistic value this how it is calculated above in ttest_1samp
(actual_mean - sample) / (sd / total_data)  
# higher the statistic value lower the probality here is 90.51 so  sample  and actual mean value does not match, it should be equal or near equal.

np.float64(90.51020889911177)

In [57]:
actual_mean

np.float64(16.821473673385437)

# null hypothesis

In [58]:
p_value

np.float64(0.0)

In [59]:
ho = f'The average total price  of all pizzas is equal to ${sample}.'
ha = f'The average total price of all pizza is not equals to ${sample}.'

In [60]:
print(f'Ho: {ho}')
print(f'Ha: {ha}')

Ho: The average total price  of all pizzas is equal to $15.
Ha: The average total price of all pizza is not equals to $15.


In [61]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. \nConclusion: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis. Required to accept null hypothesis. \nConclusion: {ho}')

Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. 
Conclusion: The average total price of all pizza is not equals to $15.


# Two sample T-Test 

# Is the average unit price of classic  pizzas and chicken pizzas are same ?

In [62]:
alpha = 0.05
classic_price = df[df['pizza_category'] == 'Classic']['unit_price']
chicken_price = df[df['pizza_category'] == 'Chicken']['unit_price']

In [63]:
# stats.ttest_ind(val1, val2,equal_var = False / True(default))
t_statistics,p_value = stats.ttest_ind(classic_price,chicken_price, equal_var = False)

In [64]:
ho = f'The average unit price of classic pizza and chicken pizza are equal.'
ha = f'The average unit price of classic pizza and chicken pizza are not equal.'

In [65]:
print(f'Ho : {ho}')
print(f'Ha : {ha}')

Ho : The average unit price of classic pizza and chicken pizza are equal.
Ha : The average unit price of classic pizza and chicken pizza are not equal.


In [66]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. \nConclusion: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis. Required to accept null hypothesis. \nConclusion: {ho}')

Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. 
Conclusion: The average unit price of classic pizza and chicken pizza are not equal.


# ANNOVA Test(Analysis of Variance)

# is the average total_price generated by all four pizza categories(Classic,chicken, supreme and veggie) differ significantly from one another?

In [67]:
alpha = 0.05
grouped_price = []
data = ['Classic','Chicken','Supreme','Veggie']
for val in data:
    price = df[df['pizza_category'] == val]['total_price']
    grouped_price.append(price)

In [68]:
grouped_price

[0        13.25
 1        16.00
 11       12.00
 14       12.00
 16       20.50
          ...  
 48600    15.25
 48604    12.50
 48605    12.00
 48607    12.00
 48617    12.00
 Name: total_price, Length: 14579, dtype: float64,
 5        20.75
 10       12.75
 24       20.75
 25       20.75
 26       20.75
          ...  
 48609    12.75
 48611    16.75
 48614    20.75
 48615    16.75
 48619    12.75
 Name: total_price, Length: 10815, dtype: float64,
 3        20.75
 6        16.50
 7        20.75
 8        16.50
 9        16.50
          ...  
 48601    41.50
 48602    20.25
 48610    20.75
 48612    16.50
 48613    12.50
 Name: total_price, Length: 11777, dtype: float64,
 2        18.50
 4        16.00
 15       12.00
 19       12.00
 21       20.75
          ...  
 48598    20.25
 48603    14.75
 48606    16.50
 48616    17.95
 48618    20.25
 Name: total_price, Length: 11449, dtype: float64]

In [69]:
t_statistics, p_value = stats.f_oneway(*grouped_price)

In [70]:
ho = 'The Average total price generated for all four pizza categories are equal.'
ha = 'The average total price generated for all four pizza categories are not equal.'

In [71]:
print(f'Ho: {ho}')
print(f'Ha: {ha}')


Ho: The Average total price generated for all four pizza categories are equal.
Ha: The average total price generated for all four pizza categories are not equal.


In [72]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. \nConclusion: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis. Required to accept null hypothesis. \nConclusion: {ho}')

Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. 
Conclusion: The average total price generated for all four pizza categories are not equal.


# Chi-Square Test

# is pizza category and pizza size dependent to one another?

In [73]:
# crosstab(col1,col2)
contingency = pd.crosstab(df['pizza_category'],df['pizza_size'])
contingency

pizza_size,L,M,S,XL,XXL
pizza_category,,,,,
Chicken,4799,3811,2205,0,0
Classic,3987,4045,5975,544,28
Supreme,4477,3977,3323,0,0
Veggie,5263,3552,2634,0,0


In [ ]:
# dof = (number_of_rows - 1) * (number_of_columns -1)

In [76]:
# stats, p_value, dof(degree of freedom), ef(expected frequency)

t_statistics,p_value,dof,ef = stats.chi2_contingency(contingency)

In [77]:
print(t_statistics,p_value,dof,ef)

3347.833491436231 0.0 12 [[4120.910942   3422.22902098 3144.6247429   121.00699301    6.22830111]
 [5555.13274373 4613.28496503 4239.06464418  163.12167832    8.39596874]
 [4487.46816125 3726.63811189 3424.34078568  131.77062937    6.78231181]
 [4362.48815302 3622.8479021  3328.96982723  128.1006993     6.59341835]]


In [78]:
ho = 'Pizza Category and Pizza Size are dependent to each other.'
ha = 'Pizza Category and Pizza Size are independent to each other.'

In [79]:
print(f'Ho : {ho}')
print(f'Ha : {ha}')

Ho : Pizza Category and Pizza Size are dependent to each other.
Ha : Pizza Category and Pizza Size are independent to each other.


In [80]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. \nConclusion: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis. Required to accept null hypothesis. \nConclusion: {ho}')

Decision: Failed to accept null hypothesis. Required to accept alternate hypothesis. 
Conclusion: Pizza Category and Pizza Size are independent to each other.
