In [3]:
#numpy indexing and slicing of vectors
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[1:4]

array([12, 13, 14])

In [6]:
arr[:4]

array([11, 12, 13, 14])

In [7]:
#NUMPY INDEXING AND SLICING OF MATRIX >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [9]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5]

array([26, 27, 28, 29, 30])

In [11]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [15]:
val = arr[0,4]
print(val)

5


In [17]:
#slicing the matrix
slice = arr[0:2 , 1:3]
slice

array([[2, 3],
       [7, 8]])

In [19]:
slice = arr[4: , 3:]
slice

array([[24, 25],
       [29, 30]])

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [25]:
#BOOLEAN INDEXING >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_idx = arr%2 == 0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])