In [3]:
# matrix_operations .....................................
import numpy as np
a = np.array([[1,2], [3,4]])
b = np.array([[5,6],[7,8]])

a @ b # this is the multiplication on the matrix using @

array([[19, 22],
       [43, 50]])

In [5]:
# Transpose
a.T

array([[1, 3],
       [2, 4]])

In [6]:
# ADVANCE ARRAY MANIPULATION.................................................

In [7]:
# stacking array --> there are3 types of stack ie vertical , horizontal and column_stack

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

np.vstack((a,b ))# vertical stack


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.column_stack((a,b)) # column stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [10]:
# SPLLITING ARRAY...................................................................

'''there are 2 split horizontal and vertical'''

a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np.hsplit(a,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [16]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]