In [4]:
# support matrix , and mathematical functions

array([1, 2, 3, 4])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr

In [5]:
#multi-dimensional matrix/arrayabs
a = [[1,2,3],[4,5,6],[7,8,9]]
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#array generation function
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [8]:
#zeros generation
arr = np.zeros((4,8)) # '''4 is row and 8 is column'''
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones((4,8)) # '''4 is row and 8 is column'''
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
#random generation function
np.random.rand(10)

array([0.90535724, 0.16381687, 0.82933184, 0.5885529 , 0.44159617,
       0.90376629, 0.42639391, 0.92446113, 0.08376221, 0.34595218])

In [13]:
#ARRAY ATTRIBUTE>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [20]:
# ARRAY METHOD >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [23]:
min = arr.min()
print(min)

1


In [25]:
max = arr.max()
print(max)

9


In [26]:
sum = arr.sum()
print(sum)

45


In [29]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [31]:
mean = arr.mean()
print(mean)

5.0


In [32]:
mean = arr.mean()
print(mean)

5.0


In [33]:
arr.argmax() #index of max value 

np.int64(8)

In [34]:
arr.argmin()

np.int64(0)

In [41]:
# RESHAPING AND RESIZING >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
a.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])