In [4]:
# support matrix , and mathematical functions

array([1, 2, 3, 4])

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
arr 

array([1, 2, 3, 4])

In [3]:
#multi-dimensional matrix/arrayabs
a = [[1,2,3],[4,5,6],[7,8,9]]
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#array generation function
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [5]:
#zeros generation
arr = np.zeros((4,8)) # '''4 is row and 8 is column'''
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.zeros(5,dtype=int)  # if u want in integer
arr

array([0, 0, 0, 0, 0])

In [13]:
arr = np.zeros((4,8),dtype=int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
arr = np.ones((4,8)) # '''4 is row and 8 is column'''
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
#random generation function
np.random.rand(10)

array([0.25082964, 0.89503364, 0.69187198, 0.84944091, 0.49127452,
       0.6239327 , 0.73563778, 0.36789898, 0.51917555, 0.0812465 ])

In [8]:
#ARRAY ATTRIBUTE>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.shape

(3, 3)

In [11]:
arr.size

9

In [12]:
# ARRAY METHOD >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [13]:
min = arr.min()
print(min)

1


In [14]:
max = arr.max()
print(max)

9


In [15]:
sum = arr.sum()
print(sum)

45


In [19]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [31]:
mean = arr.mean()
print(mean)

5.0


In [32]:
mean = arr.mean()
print(mean)

5.0


In [33]:
arr.argmax() #index of max value 

np.int64(8)

In [34]:
arr.argmin()

np.int64(0)

In [41]:
# RESHAPING AND RESIZING >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
a.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
#question asked in interview or mcq
a = [1,2,3,4]
arr = np.array(a)

In [7]:
print(a) # this is list

[1, 2, 3, 4]


In [9]:
print(arr) # this is numpy array

[1 2 3 4]
