# Slicing and reshape

In [24]:
import numpy as np

In [7]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[1:4]

array([12, 13, 14])

In [9]:
arr[:4]

array([11, 12, 13, 14])

# NUMPY INDEXING AND SLICING OF MATRIX 

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[5]

array([26, 27, 28, 29, 30])

In [13]:
arr[1]

array([ 6,  7,  8,  9, 10])

#ravel : change any dimension into 1 d array



In [ ]:
ravel_num = np.ravel(arr)
ravel_num

In [ ]:
val = arr[0,4]
print(val)

In [17]:
#slicing the matrix
slice = arr[0:2 , 1:3]
slice

array([[2, 3],
       [7, 8]])

In [19]:
slice = arr[4: , 3:]
slice

array([[24, 25],
       [29, 30]])

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# BOOLEAN INDEXING 


In [17]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_idx = arr%2 == 0
bool_idx

array([ True,  True,  True,  True,  True])

In [22]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])

In [23]:
# or u can u like this 

bool_idx = arr[arr % 2 == 0]
bool_idx

array([12, 14, 16, 18, 20])