In [15]:
#array_operation..........................................
#deep and shallow copy remember for interview

In [3]:
import numpy as np
a1 = np.array([1,2,3,4,5]) #the size of both array should same else it will throw error.
a2 = np.array([6,7,8,9,10])
result = a1+a2
print (result)


#similaly u can perform other arithematic operation --> + - * % ** // etc

[ 7  9 11 13 15]


In [8]:
#Broadcasting ...............................................

a1 = [1,2,3,4,5,6,7]
arr = np.array(a1)
result = arr + 10 #brocasting mean if u have to perform operation in all the element of arr of different shape
print (result)

[11 12 13 14 15 16 17]


In [13]:
#for other shape
a2 = np.arange(1,26).reshape(5,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
a2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [19]:
#deep and shallow copy

'''here we assigned the value a = b , and changed the value of 0 index using b then it
changed a also so this is shallow copy'''
a = [1,2,3,4,5]
b = a
b[0] = 44
b 


[44, 2, 3, 4, 5]

In [23]:
'''here if i copy the value of a to b using copy then when change of b is made it does not affect a 
this is deep copy'''

b = a.copy()
b[0] =90
b

[90, 2, 3, 4, 5]