In [2]:
#numpy solve list limitation , consumes less memory, faster and best for mathematic operation like array and matrix and handle large data.
# donot require many loop like we do to modify and append in list.
#other libraies like pandas , scikit, tensorflow, openCV and more are build on top of it.

# values like 32 is 0 dimension , [1,2,3,4,5] ---> 1D, [[],[]] as 2D and so on

In [7]:
#without numpy
salary = [10000,20000,30000]
new_salary = []

for s in salary:
      new_salary.append(s+2000)
        
print(f"{new_salary}")
    

[12000, 22000, 32000]


In [10]:
#with numpy

import numpy as np

salary = np.array([50000,60000,70000,80000])

print(salary+20000)



[ 70000  80000  90000 100000]


In [11]:
#checking dimension

In [12]:
arr =np.array(34)
arr.ndim

0

In [15]:
arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

In [16]:
#create range of number betn 1 to 10


In [20]:
import numpy as np
range = np.arange(1,10,2) #start , stop , jump
range

array([1, 3, 5, 7, 9])

In [24]:
#create a linspace betn 0 and 1
import numpy as np
arr=np.linspace(0,1,5) #start, stop, num of values between them
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
#arr full of zeros

In [31]:
import numpy as np
arr = np.zeros([2,3]) # row and column
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#arr full of ones

In [33]:
arr = np.ones([4,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
#create an array full of any value
arr =np.full(10,2) # 10 value of 2
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
arr = np.full([2,4],0.5)
arr


array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [36]:
#empty function

In [37]:
arr = np.empty([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#random

In [42]:
arr=np.random.rand(10)
arr

array([1.15994586e-01, 9.20428563e-01, 4.01034706e-01, 3.67508301e-04,
       5.16480284e-01, 6.64254645e-01, 4.13193785e-01, 5.18526554e-01,
       4.07366528e-01, 6.62912007e-02])

In [44]:
arr = np.random.rand(2,3)
arr

array([[0.34242119, 0.29363248, 0.24853859],
       [0.99778713, 0.42614034, 0.33639482]])