In [1]:
#numpy data types and type Casting

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
#converting data to float

arr =np.array([1,2,3,4,5,6],dtype =np.float64)
arr

array([1., 2., 3., 4., 5., 6.])

In [8]:
#tyoe_casting

In [9]:
arr = np.array([1,2,4])
arr.dtype

dtype('int32')

In [10]:
new_arr = arr.astype(np.float32)
new_arr

array([1., 2., 4.], dtype=float32)