In [1]:
#reshaping the array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [3]:
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#conbert to 1d

In [7]:
ravel = reshaped.ravel()
ravel


array([1, 2, 3, 4, 5, 6])

In [8]:
#flatten to convert to 1D which returns the copy
flat = reshaped.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [9]:
#### arithemetic operation on arrays ......................................................................................

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [14]:
print(a**2)

[1 4 9]


In [15]:
#universal function
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [16]:
#sin function
angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [19]:
#indexing and slicing
arr =np.array([10,20,30,40,50])
arr[::2]

array([10, 30, 50])